/******************************************************************************
 *     Copyright (C) 2026  Octavio Calleya Garcia                             *
 *                                                                            *
 *     This program is free software: you can redistribute it and/or modify   *
 *     it under the terms of the GNU General Public License as published by   *
 *     the Free Software Foundation, either version 3 of the License, or      *
 *     (at your option) any later version.                                    *
 *                                                                            *
 *     This program is distributed in the hope that it will be useful,        *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *     GNU General Public License for more details.                           *
 *                                                                            *
 *     You should have received a copy of the GNU General Public License      *
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>. *
 ******************************************************************************/

package net.transgressoft.lirp.persistence

import net.transgressoft.lirp.entity.CascadeAction
import net.transgressoft.lirp.entity.ReactiveEntityBase
import net.transgressoft.lirp.event.AggregateMutationEvent
import net.transgressoft.lirp.testing.reactiveScope
import io.kotest.assertions.throwables.shouldNotThrowAny
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.optional.shouldBePresent
import io.kotest.matchers.optional.shouldNotBePresent
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicReference

// ---------------------------------------------------------------------------
// Test-local fixture entities for @ToOneAggregate accessor behaviour
// These carry @PersistenceMapping so KSP generates their _LirpRefAccessor.
// Music-domain naming follows the canonical fixture vocabulary.
// ---------------------------------------------------------------------------

/**
 * Referenced catalog entity. A minimal music-domain entity used as a FK target
 * to verify `@ToOneAggregate` accessor navigation.
 */
@PersistenceMapping(name = "test_artist_catalog")
class TestArtistCatalog(override val id: Int, label: String) : ReactiveEntityBase<Int, TestArtistCatalog>() {
    var label: String by reactiveProperty(label)

    override val uniqueId: String get() = "test-artist-catalog-$id"

    override fun clone(): TestArtistCatalog = TestArtistCatalog(id, label)
}

/**
 * Owning entity carrying an optional FK scalar to [TestArtistCatalog] via `@ToOneAggregate`.
 * The accessor `testAlbumEntry.catalog` is generated by KSP into `TestAlbumEntry_LirpToOneExtAccessor.kt`.
 */
@PersistenceMapping(name = "test_album_entry")
class TestAlbumEntry(override val id: Int, title: String, catalogId: Int? = null) :
    ReactiveEntityBase<Int, TestAlbumEntry>() {
    var title: String by reactiveProperty(title)

    @ToOneAggregate(target = TestArtistCatalog::class, onDelete = CascadeAction.DETACH)
    var catalogId: Int? by reactiveProperty(catalogId)

    override val uniqueId: String get() = "test-album-entry-$id"

    override fun clone(): TestAlbumEntry = TestAlbumEntry(id, title, catalogId)
}

/**
 * Owning entity with a required FK scalar and `bubbleUp = true` to [TestArtistCatalog].
 *
 * `onDelete = NONE` suppresses the FK constraint check — a non-nullable FK scalar cannot use DETACH
 * (which would require nulling the column on delete). The test verifies bubble-up propagation only.
 */
@PersistenceMapping(name = "test_bubble_album")
class TestBubbleAlbum(override val id: Int, title: String, catalogId: Int) :
    ReactiveEntityBase<Int, TestBubbleAlbum>() {
    var title: String by reactiveProperty(title)

    @ToOneAggregate(target = TestArtistCatalog::class, bubbleUp = true, onDelete = CascadeAction.NONE)
    var catalogId: Int by reactiveProperty(catalogId)

    override val uniqueId: String get() = "test-bubble-album-$id"

    override fun clone(): TestBubbleAlbum = TestBubbleAlbum(id, title, catalogId)
}

/**
 * Owning entity with `onDelete = CascadeAction.CASCADE` to [TestArtistCatalog].
 */
@PersistenceMapping(name = "test_cascade_album")
class TestCascadeAlbum(override val id: Int, title: String, catalogId: Int? = null) :
    ReactiveEntityBase<Int, TestCascadeAlbum>() {
    var title: String by reactiveProperty(title)

    @ToOneAggregate(target = TestArtistCatalog::class, onDelete = CascadeAction.CASCADE)
    var catalogId: Int? by reactiveProperty(catalogId)

    override val uniqueId: String get() = "test-cascade-album-$id"

    override fun clone(): TestCascadeAlbum = TestCascadeAlbum(id, title, catalogId)
}

/**
 * Owning entity with an optional nullable FK scalar and `onDelete = RESTRICT` to [TestArtistCatalog].
 * Used to verify that RESTRICT cascade checks skip entities whose FK scalar is null.
 */
@PersistenceMapping(name = "test_restrict_album")
class TestRestrictAlbum(override val id: Int, title: String, catalogId: Int? = null) :
    ReactiveEntityBase<Int, TestRestrictAlbum>() {
    var title: String by reactiveProperty(title)

    @ToOneAggregate(target = TestArtistCatalog::class, onDelete = CascadeAction.RESTRICT)
    var catalogId: Int? by reactiveProperty(catalogId)

    override val uniqueId: String get() = "test-restrict-album-$id"

    override fun clone(): TestRestrictAlbum = TestRestrictAlbum(id, title, catalogId)
}

@LirpRepository
internal class TestArtistCatalogRepo internal constructor(context: LirpContext) :
    VolatileRepository<Int, TestArtistCatalog>(context, "TestArtistCatalogs") {
        constructor() : this(LirpContext.default)
    }

@LirpRepository
internal class TestAlbumEntryRepo internal constructor(context: LirpContext) :
    VolatileRepository<Int, TestAlbumEntry>(context, "TestAlbumEntries") {
        constructor() : this(LirpContext.default)
    }

@LirpRepository
internal class TestBubbleAlbumRepo internal constructor(context: LirpContext) :
    VolatileRepository<Int, TestBubbleAlbum>(context, "TestBubbleAlbums") {
        constructor() : this(LirpContext.default)
    }

@LirpRepository
internal class TestCascadeAlbumRepo internal constructor(context: LirpContext) :
    VolatileRepository<Int, TestCascadeAlbum>(context, "TestCascadeAlbums") {
        constructor() : this(LirpContext.default)
    }

@LirpRepository
internal class TestRestrictAlbumRepo internal constructor(context: LirpContext) :
    VolatileRepository<Int, TestRestrictAlbum>(context, "TestRestrictAlbums") {
        constructor() : this(LirpContext.default)
    }

/**
 * Tests for the KSP-generated navigation extension accessor produced by `@ToOneAggregate`.
 *
 * Verifies that the accessor-driven ref delegate stored on the entity resolves the referenced
 * entity, propagates mutations via bubble-up, and cascades deletions — all through the generated
 * extension accessor rather than a hand-written companion val.
 */
internal class ToOneAggregateExtAccessorTest : StringSpec({

    reactiveScope()

    lateinit var ctx: LirpContext

    beforeEach {
        ctx = LirpContext()
    }

    afterEach {
        ctx.close()
    }

    "TestAlbumEntry.catalog resolves referenced TestArtistCatalog after entity is added to repository" {
        val catalogRepo = TestArtistCatalogRepo(ctx)
        val albumRepo = TestAlbumEntryRepo(ctx)

        val catalog = TestArtistCatalog(1, "ECM Records")
        catalogRepo.add(catalog)

        val album = TestAlbumEntry(100, "Köln Concert", catalogId = 1)
        albumRepo.add(album)

        val ref = album.catalog
        ref.referenceId shouldBe 1
        val resolved = ref.resolve()
        resolved.shouldBePresent()
        resolved.get().label shouldBe "ECM Records"
    }

    "TestAlbumEntry.catalog referenceId matches the stored scalar" {
        val catalogRepo = TestArtistCatalogRepo(ctx)
        val albumRepo = TestAlbumEntryRepo(ctx)

        val catalog = TestArtistCatalog(2, "Blue Note")
        catalogRepo.add(catalog)

        val album = TestAlbumEntry(200, "Kind of Blue", catalogId = 2)
        albumRepo.add(album)

        album.catalog.referenceId shouldBe album.catalogId
    }

    "TestAlbumEntry.catalog resolves Optional.empty when FK scalar is null" {
        val catalogRepo = TestArtistCatalogRepo(ctx)
        val albumRepo = TestAlbumEntryRepo(ctx)

        val album = TestAlbumEntry(300, "Unknown Album", catalogId = null)
        albumRepo.add(album)

        album.catalog.resolve().shouldNotBePresent()
    }

    "TestBubbleAlbum.catalog bubbleUp=true propagates TestArtistCatalog mutation to album subscriber" {
        val catalogRepo = TestArtistCatalogRepo(ctx)
        val albumRepo = TestBubbleAlbumRepo(ctx)

        val catalog = TestArtistCatalog(10, "Verve")
        catalogRepo.add(catalog)

        val album = TestBubbleAlbum(1000, "Getz/Gilberto", catalogId = 10)
        albumRepo.add(album)

        val receivedEvent = AtomicReference<AggregateMutationEvent<*, *>>(null)
        val latch = CountDownLatch(1)

        album.subscribeAsync { event ->
            if (event is AggregateMutationEvent<*, *>) {
                receivedEvent.set(event)
                latch.countDown()
            }
        }

        catalog.label = "Verve Records"

        latch.await(2, TimeUnit.SECONDS) shouldBe true
        receivedEvent.get().refName shouldBe "catalog"
    }

    "TestCascadeAlbum CASCADE deletion removes the referenced TestArtistCatalog" {
        val catalogRepo = TestArtistCatalogRepo(ctx)
        val cascadeAlbumRepo = TestCascadeAlbumRepo(ctx)

        val catalog = TestArtistCatalog(20, "Deutsche Grammophon")
        catalogRepo.add(catalog)

        val album = TestCascadeAlbum(2000, "Beethoven Sonatas", catalogId = 20)
        cascadeAlbumRepo.add(album)

        cascadeAlbumRepo.remove(album)

        catalogRepo.findById(20).shouldNotBePresent()
        cascadeAlbumRepo.findById(2000).shouldNotBePresent()
    }

    "TestAlbumEntry.catalog DETACH removal leaves referenced TestArtistCatalog intact" {
        val catalogRepo = TestArtistCatalogRepo(ctx)
        val albumRepo = TestAlbumEntryRepo(ctx)

        val catalog = TestArtistCatalog(30, "Columbia")
        catalogRepo.add(catalog)

        val album = TestAlbumEntry(3000, "Bridge Over Troubled Water", catalogId = 30)
        albumRepo.add(album)

        albumRepo.remove(album)

        catalogRepo.findById(30).shouldBePresent()
        albumRepo.findById(3000).shouldNotBePresent()
    }

    "TestAlbumEntry.catalog accessor throws IllegalStateException when entity is not in a repository" {
        val album = TestAlbumEntry(400, "Orphaned", catalogId = 5)

        shouldThrow<IllegalStateException> { album.catalog }
            .message shouldContain "Ensure the entity is added to its repository"
    }

    "TestRestrictAlbum RESTRICT delete does not throw when another album has a null optional FK scalar" {
        val catalogRepo = TestArtistCatalogRepo(ctx)
        val restrictAlbumRepo = TestRestrictAlbumRepo(ctx)

        val catalog = TestArtistCatalog(50, "Nonesuch Records")
        catalogRepo.add(catalog)

        // album1 references the catalog; album2 has a null FK (references nothing)
        val album1 = TestRestrictAlbum(5000, "Nonesuch Album", catalogId = 50)
        val album2 = TestRestrictAlbum(5001, "Unlinked Album", catalogId = null)
        restrictAlbumRepo.add(album1)
        restrictAlbumRepo.add(album2)

        // Removing album1 must not throw: album2 has a null FK so it does not reference the catalog
        shouldNotThrowAny { restrictAlbumRepo.remove(album1) }

        catalogRepo.findById(50).shouldBePresent()
        restrictAlbumRepo.findById(5000).shouldNotBePresent()
        restrictAlbumRepo.findById(5001).shouldBePresent()
    }

    "TestRestrictAlbum RESTRICT delete throws when another album with non-null FK still references the catalog" {
        val catalogRepo = TestArtistCatalogRepo(ctx)
        val restrictAlbumRepo = TestRestrictAlbumRepo(ctx)

        val catalog = TestArtistCatalog(60, "ECM Records")
        catalogRepo.add(catalog)

        val album1 = TestRestrictAlbum(6000, "ECM Album A", catalogId = 60)
        val album2 = TestRestrictAlbum(6001, "ECM Album B", catalogId = 60)
        restrictAlbumRepo.add(album1)
        restrictAlbumRepo.add(album2)

        // Both albums reference the same catalog — removing album1 is blocked by album2
        val ex = shouldThrow<IllegalStateException> { restrictAlbumRepo.remove(album1) }
        ex.message shouldContain "Cannot cascade-delete"
    }

    "TestRestrictAlbum close() on entity with null FK does not throw" {
        val restrictAlbumRepo = TestRestrictAlbumRepo(ctx)

        val album = TestRestrictAlbum(7000, "Unlinked Album", catalogId = null)
        restrictAlbumRepo.add(album)

        // Close must not throw even though the FK scalar is null
        shouldNotThrowAny { album.close() }
    }

    "TestAlbumEntry close() before being added to a repository does not allocate to-one ref delegates" {
        // Regression for WR-01: cancelAllBubbleUp must not call getOrComputeToOneRef (which
        // allocates and stores a delegate) when no delegate exists yet.
        val album = TestAlbumEntry(8000, "Never-added Album", catalogId = 42)

        // Close before adding to any repository — must not throw and must not create a delegate
        shouldNotThrowAny { album.close() }
        // After close, getToOneRef must still throw (no delegate was created during teardown)
        shouldThrow<IllegalStateException> { album.catalog }
            .message shouldContain "Ensure the entity is added to its repository"
    }
})