plugins {
    id 'com.google.devtools.ksp'
    id 'java-test-fixtures'
}

description = 'LIRP Core'

ktlint {
    filter {
        exclude { it.file.path.contains("/generated/") }
    }
}

dependencies {
    api project(path: ':lirp-api')
    api libs.kotlin.stdlib

    implementation libs.jsr305
    implementation libs.kotlin.logging
    implementation libs.coroutines.slf4j
    implementation libs.slf4j.api
    implementation libs.kotlin.reflect
    implementation libs.serialization.json

    ksp project(path: ':lirp-ksp')
    kspTest project(path: ':lirp-ksp')
    kspTestFixtures project(path: ':lirp-ksp')

    testFixturesImplementation project(path: ':lirp-api')
    testFixturesImplementation libs.kotlin.stdlib
    testFixturesImplementation libs.bundles.kotest
    testFixturesImplementation libs.bundles.logback
    testFixturesImplementation libs.coroutines.test
    testFixturesImplementation libs.serialization.json

    testImplementation testFixtures(project(':lirp-core'))

    testImplementation platform(libs.junit.bom)
    testImplementation libs.logback.core
    testImplementation libs.logback.classic
    testImplementation libs.bundles.kotest
    testImplementation libs.mockk
    testImplementation libs.coroutines.test
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

tasks.withType(Test).configureEach {
    systemProperty 'kotest.framework.config.fqn', 'net.transgressoft.lirp.testing.CoreKotestProjectConfig'
    def excludeTags = project.findProperty('kotest.tags.exclude') as String
    if (excludeTags) {
        systemProperty 'kotest.tags.exclude', excludeTags
    }
}
