/******************************************************************************
 *     Copyright (C) 2025  Octavio Calleya Garcia                             *
 *                                                                            *
 *     This program is free software: you can redistribute it and/or modify   *
 *     it under the terms of the GNU General Public License as published by   *
 *     the Free Software Foundation, either version 3 of the License, or      *
 *     (at your option) any later version.                                    *
 *                                                                            *
 *     This program is distributed in the hope that it will be useful,        *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *     GNU General Public License for more details.                           *
 *                                                                            *
 *     You should have received a copy of the GNU General Public License      *
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>. *
 ******************************************************************************/

package net.transgressoft.lirp.persistence

import net.transgressoft.lirp.entity.CascadeAction

/**
 * Compile-time resolved descriptor for a collection-typed `@Aggregate` property, pairing
 * the reference name with a direct IDs getter function, a direct delegate getter function, and
 * metadata about the reference's behavior.
 *
 * Instances are generated by the LIRP KSP processor at compile time, eliminating runtime
 * reflection for both ID collection access and delegate access. Parallel to [RefEntry] but
 * covers collection-typed references instead of single-entity references.
 *
 * @param K the referenced entities' ID type — must be [Comparable]
 * @param T the entity type that declares the collection reference
 * @property refName the name of the reference property (defaults to the property name)
 * @property idsGetter direct accessor function returning all referenced entity IDs — compiled
 *   to a regular method call accessing the backing field's collection of IDs, not reflection
 * @property delegateGetter KSP-generated lambda returning the [AggregateCollectionRef]
 *   delegate instance — either an `AggregateListRefDelegate` (when [isOrdered] is `true`) or an
 *   `AggregateSetRefDelegate` (when [isOrdered] is `false`). Used by [RegistryBase] to call
 *   registry binding and cascade operations without any `java.lang.reflect` field access.
 *   Star-projected because collection references on the same entity may reference different
 *   entity types with different K types.
 * @property referencedClass the [Class] of the referenced entity type, used for registry lookup
 * @property cascadeAction the [CascadeAction] to execute when the owning entity is deleted;
 *   defaults to [CascadeAction.NONE] per design decision D-06
 * @property isOrdered `true` if the reference is ordered and allows duplicates (List semantics);
 *   `false` if the reference enforces uniqueness (Set semantics)
 */
data class CollectionRefEntry<K : Comparable<K>, T>(
    val refName: String,
    val idsGetter: (T) -> Collection<K>,
    val delegateGetter: (T) -> AggregateCollectionRef<*, *>,
    val referencedClass: Class<*>,
    val cascadeAction: CascadeAction,
    val isOrdered: Boolean
)