/******************************************************************************
 *     Copyright (C) 2025  Octavio Calleya Garcia                             *
 *                                                                            *
 *     This program is free software: you can redistribute it and/or modify   *
 *     it under the terms of the GNU General Public License as published by   *
 *     the Free Software Foundation, either version 3 of the License, or      *
 *     (at your option) any later version.                                    *
 *                                                                            *
 *     This program is distributed in the hope that it will be useful,        *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *     GNU General Public License for more details.                           *
 *                                                                            *
 *     You should have received a copy of the GNU General Public License      *
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>. *
 ******************************************************************************/

package net.transgressoft.lirp.persistence

/**
 * Compile-time resolved descriptor for an [@Indexed][Indexed] property, pairing the index name
 * with a direct property getter function. Instances are generated by the LIRP KSP processor
 * at compile time, eliminating runtime reflection for property value access.
 *
 * Index values are heterogeneous (different properties can have different types), so no K type
 * parameter is added — the getter returns [Any?] and callers handle the type appropriately.
 *
 * @param T The entity type
 * @property indexName The resolved index name (from [Indexed.name] or the property name)
 * @property propertyName The property name of the entity
 * @property sorted `true` when the source `@Indexed(sorted = true)`; consumed by `RegistryBase.discoverIndexes`
 *   to select between `ConcurrentHashMap` and `ConcurrentSkipListMap` bucket storage.
 * @property getter Direct property accessor function — compiled to a regular method call, not reflection
 */
data class IndexEntry<T>(
    val indexName: String,
    val propertyName: String = indexName,
    val sorted: Boolean = false,
    val getter: (T) -> Any?
)