/******************************************************************************
 *     Copyright (C) 2025  Octavio Calleya Garcia                             *
 *                                                                            *
 *     This program is free software: you can redistribute it and/or modify   *
 *     it under the terms of the GNU General Public License as published by   *
 *     the Free Software Foundation, either version 3 of the License, or      *
 *     (at your option) any later version.                                    *
 *                                                                            *
 *     This program is distributed in the hope that it will be useful,        *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *     GNU General Public License for more details.                           *
 *                                                                            *
 *     You should have received a copy of the GNU General Public License      *
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>. *
 ******************************************************************************/

package net.transgressoft.lirp.persistence

import kotlinx.serialization.KSerializer

/**
 * Contract for KSP-generated FxScalar accessor classes.
 *
 * Each entity class with [FxScalarPropertyDelegate] properties gets a compile-time generated
 * implementation of this interface. The generated class is named `{EntityName}_LirpFxScalarAccessor`
 * and lives in the same package as the entity, discovered at runtime via a convention-based
 * [Class.forName] lookup.
 *
 * The generated [entries] contain direct property getter and setter lambdas compiled to regular
 * method calls, completely avoiding `java.lang.reflect.Method` access and the `--add-opens`
 * JVM flag requirement.
 *
 * @param T The entity type this accessor was generated for
 */
interface LirpFxScalarAccessor<T> {

    /**
     * Pre-built entries with direct get/set lambdas and compile-time resolved serializers
     * for all [FxScalarPropertyDelegate] properties of the entity.
     */
    val entries: List<FxScalarEntry<T>>
}

/**
 * Compile-time resolved descriptor for a [FxScalarPropertyDelegate] property, pairing the
 * property name with direct accessor lambdas and a pre-resolved serializer. Instances are
 * generated by the LIRP KSP processor at compile time, eliminating runtime reflection for
 * FxScalar property access.
 *
 * @param T The entity type
 * @property name The property name as declared in the entity class
 * @property getter Direct property accessor — compiled to a regular method call, not reflection
 * @property setter Direct property mutator — compiled to a regular method call, not reflection
 * @property serializer The [KSerializer] resolved at compile time for the property's value type
 */
data class FxScalarEntry<T>(
    val name: String,
    val getter: (T) -> Any?,
    val setter: (T, Any?) -> Unit,
    val serializer: KSerializer<Any?>
)