/******************************************************************************
 *     Copyright (C) 2025  Octavio Calleya Garcia                             *
 *                                                                            *
 *     This program is free software: you can redistribute it and/or modify   *
 *     it under the terms of the GNU General Public License as published by   *
 *     the Free Software Foundation, either version 3 of the License, or      *
 *     (at your option) any later version.                                    *
 *                                                                            *
 *     This program is distributed in the hope that it will be useful,        *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *     GNU General Public License for more details.                           *
 *                                                                            *
 *     You should have received a copy of the GNU General Public License      *
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>. *
 ******************************************************************************/

package net.transgressoft.lirp.persistence

import net.transgressoft.lirp.entity.CascadeAction

/**
 * Compile-time resolved descriptor for a [@ReactiveEntityRef][ReactiveEntityRef] property, pairing
 * the reference name with a direct ID getter function, a direct delegate getter function, and
 * metadata about the reference's behavior.
 *
 * Instances are generated by the LIRP KSP processor at compile time, eliminating runtime reflection
 * for both ID value access and delegate access. Mirrors [IndexEntry] but extends it with
 * aggregate-reference-specific fields.
 *
 * Moved from `lirp-api` to `lirp-core` because [delegateGetter] returns [AggregateRefDelegate],
 * which is a `lirp-core` type.
 *
 * @param T The entity type that declares the reference
 * @param K The referenced entity's ID type — must be [Comparable]. Null IDs are prohibited at the
 *   type level; all referenced entity IDs must be non-null.
 * @property refName The name of the reference (defaults to the property name)
 * @property idGetter Direct accessor function for the referenced entity's ID — compiled to a
 *   regular method call accessing the backing field's [AggregateRefDelegate.referenceId], not reflection.
 *   Returns [K] (non-null) since null IDs are not permitted.
 * @property delegateGetter KSP-generated lambda that directly returns the [AggregateRefDelegate]
 *   instance from the entity's `propertyName${'$'}delegate` backing field. Used by [RegistryBase] to
 *   call [AggregateRefDelegate.bindRegistry], [AggregateRefDelegate.wireBubbleUp],
 *   [AggregateRefDelegate.executeCascade], and [AggregateRefDelegate.cancelBubbleUp] without
 *   any `java.lang.reflect` field access.
 * @property referencedClass The [Class] of the referenced entity type, used for registry lookup
 * @property bubbleUp Whether mutation events from the referenced entity propagate to the referencing
 *   entity's subscribers as [net.transgressoft.lirp.event.AggregateMutationEvent]
 * @property cascadeAction The [CascadeAction] to execute when the referencing entity is deleted
 */
data class RefEntry<T, K : Comparable<K>>(
    val refName: String,
    val idGetter: (T) -> K,
    val delegateGetter: (T) -> AggregateRefDelegate<*, K>,
    val referencedClass: Class<*>,
    val bubbleUp: Boolean,
    val cascadeAction: CascadeAction
)