/******************************************************************************
 *     Copyright (C) 2025  Octavio Calleya Garcia                             *
 *                                                                            *
 *     This program is free software: you can redistribute it and/or modify   *
 *     it under the terms of the GNU General Public License as published by   *
 *     the Free Software Foundation, either version 3 of the License, or      *
 *     (at your option) any later version.                                    *
 *                                                                            *
 *     This program is distributed in the hope that it will be useful,        *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *     GNU General Public License for more details.                           *
 *                                                                            *
 *     You should have received a copy of the GNU General Public License      *
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>. *
 ******************************************************************************/

package net.transgressoft.lirp.persistence

import kotlin.reflect.KProperty1

/**
 * Compile-time descriptor for a collection-typed [@Aggregate][Aggregate] property used by the
 * cross-aggregate Query DSL (`via … anyMatch / allMatch / noneMatch`).
 *
 * Instances are generated by [net.transgressoft.lirp.persistence] KSP processors and consumed at
 * runtime by the registry to resolve a `KProperty1` reference inside a `via` operator chain to the
 * concrete child registry. Pure data — no behavior, no fold logic.
 *
 * @param K the referenced entities' ID type — must be [Comparable]
 * @param TParent the entity type that declares the collection reference
 * @property refName the property name (defaults to the Kotlin property name)
 * @property parentProp the typed [KProperty1] reference that yields the referenced IDs at query time;
 *   the planner reads `referenceIds` live through this property to honour the detached-child contract
 * @property referencedClass the [Class] of the referenced entity type, used for child-registry lookup
 */
data class ViaCollectionAccessorEntry<K : Comparable<K>, TParent>(
    val refName: String,
    val parentProp: KProperty1<TParent, Collection<K>>,
    val referencedClass: Class<*>
)

/**
 * Compile-time descriptor for a single-entity [@Aggregate][Aggregate] property used by the
 * cross-aggregate Query DSL (`via … where`).
 *
 * Instances are generated by the LIRP KSP processor and consumed at runtime by the registry to
 * resolve a `KProperty1` reference inside a `via` operator chain to the concrete child registry.
 * The `parentProp` returns `K?` because single-entity refs are nullable by contract; the planner
 * silently excludes parents whose ref is `null` — a null FK means the relationship is unset.
 *
 * @param K the referenced entity's ID type — must be [Comparable]
 * @param TParent the entity type that declares the single-entity reference
 * @property refName the property name (defaults to the Kotlin property name)
 * @property parentProp the typed [KProperty1] reference that yields the referenced ID (or `null`)
 *   at query time
 * @property referencedClass the [Class] of the referenced entity type, used for child-registry lookup
 */
data class ViaSingleAccessorEntry<K : Comparable<K>, TParent>(
    val refName: String,
    val parentProp: KProperty1<TParent, K?>,
    val referencedClass: Class<*>
)