/******************************************************************************
 *     Copyright (C) 2025  Octavio Calleya Garcia                             *
 *                                                                            *
 *     This program is free software: you can redistribute it and/or modify   *
 *     it under the terms of the GNU General Public License as published by   *
 *     the Free Software Foundation, either version 3 of the License, or      *
 *     (at your option) any later version.                                    *
 *                                                                            *
 *     This program is distributed in the hope that it will be useful,        *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *     GNU General Public License for more details.                           *
 *                                                                            *
 *     You should have received a copy of the GNU General Public License      *
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>. *
 ******************************************************************************/

package net.transgressoft.lirp.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSTypeAlias

private const val INDEXED_ANNOTATION_FQN = "net.transgressoft.lirp.persistence.Indexed"
private const val FX_SCALAR_DELEGATE_FQN = "net.transgressoft.lirp.persistence.FxScalarPropertyDelegate"
private const val REACTIVE_ENTITY_BASE_FQN = "net.transgressoft.lirp.entity.ReactiveEntityBase"
private const val IDENTIFIABLE_ENTITY_FQN = "net.transgressoft.lirp.entity.IdentifiableEntity"

/**
 * KSP processor that validates accessor completeness for entity classes.
 *
 * Emits a build error when:
 * - An entity class has `@Indexed` delegate properties but no `LirpIndexAccessor` was generated by [IndexedProcessor].
 * - An entity class has [FxScalarPropertyDelegate][net.transgressoft.lirp.persistence.FxScalarPropertyDelegate]
 *   delegate properties but no `LirpFxScalarAccessor` was generated by [FxScalarAccessorProcessor].
 *
 * This processor catches missing KSP processor configuration at compile time rather than
 * silently producing empty indexes or failing at runtime.
 *
 * **Round-2 deferral strategy:** In round 1, when entities needing validation are found, this
 * processor writes a tiny sentinel file to force KSP to run a second round. Accessor generator
 * processors ([IndexedProcessor], [FxScalarAccessorProcessor]) also generate their output in round 1.
 * In round 2, all generated accessor classes are visible in the resolver, and this validator
 * uses [Resolver.getClassDeclarationByName] to check whether each expected accessor is present.
 *
 * Entity metadata extracted in round 1 is stored as plain strings rather than [KSClassDeclaration]
 * references, which become invalid across KSP rounds due to PSI lifetime constraints.
 */
class LirpAccessorValidationProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    private var round = 0
    private var deferredEntities: List<EntityValidationInfo> = emptyList()

    /**
     * Holds plain-string metadata about an entity that needs accessor validation.
     * Plain strings (not KSP symbols) are used here because [KSClassDeclaration] objects
     * are invalidated between KSP rounds due to PSI lifetime constraints.
     *
     * @param simpleName simple class name for use in error messages
     * @param accessorFqnPrefix fully qualified prefix before the accessor suffix, e.g. `test.OrderEntity`
     * @param hasIndexed whether the entity has `@Indexed` delegate properties
     * @param hasFxScalar whether the entity has [FxScalarPropertyDelegate] delegate properties
     */
    private data class EntityValidationInfo(
        val simpleName: String,
        val accessorFqnPrefix: String,
        val hasIndexed: Boolean,
        val hasFxScalar: Boolean
    )

    override fun process(resolver: Resolver): List<KSAnnotated> {
        round++

        if (round == 1) {
            // Round 1: collect entities that need validation.
            // Other generators (IndexedProcessor, FxScalarAccessorProcessor) also run in round 1 and
            // produce accessor files. Those classes are visible via resolver in round 2 only.
            deferredEntities = collectEntitiesNeedingAccessors(resolver)
            if (deferredEntities.isEmpty()) return emptyList()
            // Write a sentinel file to guarantee KSP runs a second round even if no other processor
            // generated any files. Without a generated file, KSP may skip round 2 entirely.
            writeSentinel()
            return emptyList()
        }

        // Round 2+: accessor classes generated in round 1 are now visible in the resolver.
        // Validate once when deferred entities are present, then clear to avoid duplicate errors
        // if KSP triggers additional rounds (e.g. on incremental builds or multi-processor setups).
        if (deferredEntities.isNotEmpty()) {
            validateAccessorCompleteness(deferredEntities, resolver)
            deferredEntities = emptyList()
        }

        return emptyList()
    }

    /**
     * Writes a trivial Kotlin file to force KSP into a second processing round.
     *
     * KSP only runs round 2 if at least one new file was generated in round 1. Since the validator
     * itself does not generate accessor code, it must produce this sentinel file when entities requiring
     * validation are found, guaranteeing that round 2 runs and accessor classes from round 1 become visible.
     */
    private fun writeSentinel() {
        val file =
            codeGenerator.createNewFile(
                dependencies = Dependencies(false),
                packageName = "net.transgressoft.lirp.ksp.internal",
                fileName = "LirpValidationSentinel"
            )
        file.write("// Generated by LirpAccessorValidationProcessor — do not edit.\n".toByteArray())
        file.close()
    }

    private fun collectEntitiesNeedingAccessors(resolver: Resolver): List<EntityValidationInfo> {
        val indexedClassFqns =
            resolver.getSymbolsWithAnnotation(INDEXED_ANNOTATION_FQN)
                .filterIsInstance<KSPropertyDeclaration>()
                .mapNotNull { it.parentDeclaration as? KSClassDeclaration }
                .mapNotNull { it.qualifiedName?.asString() }
                .toSet()

        // Use getNewFiles() rather than getAllFiles() so that only source files belonging to the
        // current compilation unit are scanned. getAllFiles() includes all files visible to the
        // resolver (including transitive classpath sources), causing lirp-core entities to be
        // spuriously matched while the user's own entity classes are missed.
        return resolver.getNewFiles()
            .flatMap { it.declarations }
            .filterIsInstance<KSClassDeclaration>()
            .flatMap { allClassDeclarations(it) }
            .filter { !isAnonymousOrLocal(it) && isLirpEntity(it) }
            .mapNotNull { classDecl ->
                val fqn = classDecl.qualifiedName?.asString() ?: return@mapNotNull null
                val hasIndexed = fqn in indexedClassFqns
                val hasFxScalar = classDecl.getAllProperties().any { isFxScalarProperty(it) }
                if (hasIndexed || hasFxScalar) {
                    // Build the accessor FQN prefix from package + jvm binary name now, while
                    // the class declaration is still valid. Stored as a string to survive round 2.
                    val packageName = classDecl.packageName.asString()
                    val jvmName = classDecl.jvmBinaryName()
                    val accessorFqnPrefix = if (packageName.isEmpty()) jvmName else "$packageName.$jvmName"
                    EntityValidationInfo(
                        simpleName = classDecl.simpleName.asString(),
                        accessorFqnPrefix = accessorFqnPrefix,
                        hasIndexed = hasIndexed,
                        hasFxScalar = hasFxScalar
                    )
                } else {
                    null
                }
            }
            .toList()
    }

    private fun allClassDeclarations(classDecl: KSClassDeclaration): Sequence<KSClassDeclaration> =
        sequence {
            yield(classDecl)
            classDecl.declarations.filterIsInstance<KSClassDeclaration>().forEach {
                yieldAll(allClassDeclarations(it))
            }
        }

    private fun isAnonymousOrLocal(classDecl: KSClassDeclaration): Boolean =
        (classDecl.classKind == ClassKind.OBJECT && classDecl.simpleName.asString().isEmpty()) ||
            classDecl.qualifiedName == null

    private fun isLirpEntity(classDecl: KSClassDeclaration): Boolean =
        isTypeByFqn(classDecl, REACTIVE_ENTITY_BASE_FQN) || isTypeByFqn(classDecl, IDENTIFIABLE_ENTITY_FQN)

    private fun isTypeByFqn(
        classDecl: KSClassDeclaration,
        fqn: String,
        visited: MutableSet<String> = mutableSetOf()
    ): Boolean {
        val declFqn = classDecl.qualifiedName?.asString() ?: return false
        if (!visited.add(declFqn)) return false
        if (declFqn == fqn) return true
        for (superType in classDecl.superTypes) {
            val declaration = superType.resolve().declaration
            if (declaration is KSClassDeclaration && isTypeByFqn(declaration, fqn, visited)) return true
        }
        return false
    }

    private fun isFxScalarProperty(prop: KSPropertyDeclaration): Boolean = isFxScalarType(prop.type.resolve())

    private fun isFxScalarType(type: KSType, visited: MutableSet<String> = mutableSetOf()): Boolean {
        val declaration = type.declaration
        if (declaration is KSTypeAlias) return isFxScalarType(declaration.type.resolve(), visited)
        val declFqn = declaration.qualifiedName?.asString() ?: return false
        if (!visited.add(declFqn)) return false
        if (declFqn == FX_SCALAR_DELEGATE_FQN) return true
        if (declaration is KSClassDeclaration) {
            for (superType in declaration.superTypes) {
                if (isFxScalarType(superType.resolve(), visited)) return true
            }
        }
        return false
    }

    /**
     * Checks each entity for the presence of its expected accessor class by FQN lookup via the resolver.
     * In round 2, all accessor classes generated in round 1 by [IndexedProcessor] and
     * [FxScalarAccessorProcessor] are visible to [Resolver.getClassDeclarationByName].
     */
    private fun validateAccessorCompleteness(entities: List<EntityValidationInfo>, resolver: Resolver) {
        for (info in entities) {
            if (info.hasIndexed) {
                val accessorFqn = "${info.accessorFqnPrefix}_LirpIndexAccessor"
                if (resolver.getClassDeclarationByName(resolver.getKSNameFromString(accessorFqn)) == null) {
                    logger.error(
                        "Entity '${info.simpleName}' has @Indexed delegates but no generated LirpIndexAccessor. " +
                            "Ensure lirp-ksp is applied as a KSP processor in your build.gradle."
                    )
                }
            }

            if (info.hasFxScalar) {
                val accessorFqn = "${info.accessorFqnPrefix}_LirpFxScalarAccessor"
                if (resolver.getClassDeclarationByName(resolver.getKSNameFromString(accessorFqn)) == null) {
                    logger.error(
                        "Entity '${info.simpleName}' has FxScalar delegates but no generated LirpFxScalarAccessor. " +
                            "Ensure lirp-ksp is applied as a KSP processor in your build.gradle."
                    )
                }
            }
        }
    }
}