/******************************************************************************
 *     Copyright (C) 2025  Octavio Calleya Garcia                             *
 *                                                                            *
 *     This program is free software: you can redistribute it and/or modify   *
 *     it under the terms of the GNU General Public License as published by   *
 *     the Free Software Foundation, either version 3 of the License, or      *
 *     (at your option) any later version.                                    *
 *                                                                            *
 *     This program is distributed in the hope that it will be useful,        *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *     GNU General Public License for more details.                           *
 *                                                                            *
 *     You should have received a copy of the GNU General Public License      *
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>. *
 ******************************************************************************/

package net.transgressoft.lirp.persistence

import net.transgressoft.lirp.entity.CascadeAction

/**
 * Compile-time resolved descriptor for a [@ReactiveEntityRef][ReactiveEntityRef] property, pairing
 * the reference name with a direct ID getter function and metadata about the reference's behavior.
 *
 * Instances are generated by the LIRP KSP processor at compile time, eliminating runtime reflection
 * for ID value access. Mirrors [IndexEntry] but extends it with aggregate-reference-specific fields.
 *
 * @param T The entity type that declares the reference
 * @property refName The name of the reference (defaults to the property name)
 * @property idGetter Direct accessor function for the referenced entity's ID — compiled to a
 *   regular method call, not reflection
 * @property referencedClass The [Class] of the referenced entity type, used for repository lookup
 * @property bubbleUp Whether mutation events from the referenced entity propagate to the referencing
 *   entity's subscribers as [net.transgressoft.lirp.event.AggregateMutationEvent]
 * @property cascadeAction The [CascadeAction] to execute when the referencing entity is deleted
 */
data class RefEntry<T>(
    val refName: String,
    val idGetter: (T) -> Any?,
    val referencedClass: Class<*>,
    val bubbleUp: Boolean,
    val cascadeAction: CascadeAction
)